name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's Changed
            - Initial release of Livestock360
            - AI-powered animal disease detection
            - Multi-platform support (Mobile, Backend, Web)
            
            ## Features
            - Animal disease detection and diagnosis
            - Veterinary appointment management
            - AI chatbot for livestock care
            - Symptom checker
            - Vaccine management
            - Task scheduling and reminders
            
          draft: false
          prerelease: false